#!/usr/bin/env python3
"""Trim graph.json into the JS data file the web viewer loads (window.LLM_LINEAGE)."""
import json, os, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
g = json.load(open(f"{ROOT}/data/graph.json"))
KEEP = ["key", "title", "base_title", "org", "date", "month", "generation", "model_type", "architecture_class", "attention_class", "is_moe", "num_experts",
        "experts_per_tok", "shared_experts", "dense_prefix_layers", "hybrid_mixer", "hybrid_ratio", "linear_layers", "full_attention_layers_in_hybrid",
        "sparse_attention", "swa", "swa_ratio", "swa_local_layers", "swa_global_layers", "mtp", "mtp_layers", "qk_norm", "gated_attention", "nope",
        "position_encoding", "mhc", "kv_sharing", "per_layer_embeddings", "looped", "shortconv", "attention_sinks", "chunked_attention", "latent_moe",
        "encoder_decoder", "num_layers", "hidden_size", "num_heads", "num_kv_heads", "head_dim", "intermediate_size", "vocab_size",
        "max_position_embeddings", "tie_embeddings", "activation", "norm_type", "primary_parent", "is_terminal", "is_root", "scale_copy", "merged_into", "aliases",
        "config_source", "provenance",
        "rope_theta", "rope_scaling_type", "rope_scaling_factor", "original_max_position_embeddings", "partial_rotary_factor", "rotary_dim", "norm_eps", "hidden_act",
        "attention_bias", "mlp_bias", "moe_intermediate_size", "shared_expert_intermediate_size", "moe_layers", "moe_layer_freq", "routed_scaling_factor", "norm_topk_prob",
        "topk_method", "expert_groups", "topk_group", "router_scoring", "router_aux_loss_coef", "moe_latent_size", "zero_experts", "q_lora_rank", "kv_lora_rank", "qk_rope_head_dim",
        "qk_nope_head_dim", "v_head_dim", "gqa_ratio", "sliding_window", "index_topk", "index_n_heads", "index_head_dim", "index_share", "compress_ratios", "hc_streams",
        "mamba_num_heads", "mamba_head_dim", "ssm_state_size", "mamba_n_groups", "conv_kernel", "linear_num_key_heads", "linear_num_value_heads", "linear_key_head_dim",
        "linear_value_head_dim", "kv_shared_layers", "hidden_size_per_layer_input", "loop_passes", "final_logit_softcapping", "attn_logit_softcapping", "query_pre_attn_scalar",
        "swiglu_limit", "dtype", "transformers_version", "post_norm", "recurrent_only", "layer_schedule", "outer_model_type", "num_config_keys", "num_architecture_keys", "config_canonical", "config_canonical_raw_key"]
ALWAYS = ["attention_class", "swa", "is_moe", "mtp", "qk_norm", "gated_attention", "is_terminal", "is_root", "generation"]
import re


def display_name(title):
    """Model name without the parameter count: 'Qwen3 (235B-A22B)' -> 'Qwen3', 'ZAYA1-8B' -> 'ZAYA1'."""
    t = re.sub(r"\s*\([^)]*\)\s*$", "", title)
    t = re.sub(r"[\s-]+\d+(?:\.\d+)?[BMT](?:-A\d+(?:\.\d+)?B)?$", "", t)
    return t.strip()


nodes = []
for m in g["nodes"]:
    n = {k: m.get(k) for k in KEEP if m.get(k) not in (None, False, "", [])}
    n["name"] = display_name(m["title"])
    for k in ALWAYS:
        n[k] = m[k]
    n["gallery"] = {k: m["gallery"].get(k) for k in ["card_url", "config_url", "report_url", "scale", "attention", "layer_mix"]}
    nodes.append(n)
edges = [{k: e[k] for k in ["source", "target", "type", "score", "jaccard", "shared", "traits", "why", "bonus"] if k in e} for e in g["edges"]]
out = {k: g[k] for k in ["generated", "source", "n_gallery", "origin_threshold"]}
out["nodes"], out["edges"] = nodes, edges
import schema
out["schema_groups"] = schema.GROUPS
out["schema_sections"] = schema.SECTIONS
out["schema_scale"] = sorted(schema.SCALE)
out["schema_tuning"] = sorted(schema.TUNING)
out["schema_not_a_change"] = sorted(schema.NOT_A_CHANGE)
out["schema_presence"] = sorted(schema.PRESENCE)
out["schema_mechanism"] = sorted(schema.MECHANISM)
js = "/* Generated by export_web.py — https://github.com/wenhaochai/llm-architecture-lineage */\nwindow.LLM_LINEAGE = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n"
targets = sys.argv[1:] or [f"{ROOT}/web/data.js"]
for t in targets:
    open(t, "w").write(js)
    print("wrote", t, len(js) // 1024, "KB,", len(nodes), "nodes,", len(edges), "edges")
