#!/usr/bin/env python3
"""Trim graph.json into the JS data file the web viewer loads (window.LLM_LINEAGE)."""
import json, os, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
g = json.load(open(f"{ROOT}/data/graph.json"))
KEEP = ["key", "title", "org", "date", "month", "generation", "model_type", "architecture_class", "attention_class", "is_moe", "num_experts",
        "experts_per_tok", "shared_experts", "dense_prefix_layers", "hybrid_mixer", "hybrid_ratio", "linear_layers", "full_attention_layers_in_hybrid",
        "sparse_attention", "swa", "swa_ratio", "swa_local_layers", "swa_global_layers", "mtp", "mtp_layers", "qk_norm", "gated_attention", "nope",
        "position_encoding", "mhc", "kv_sharing", "per_layer_embeddings", "looped", "shortconv", "attention_sinks", "chunked_attention", "latent_moe",
        "encoder_decoder", "num_layers", "hidden_size", "num_heads", "num_kv_heads", "head_dim", "intermediate_size", "vocab_size",
        "max_position_embeddings", "tie_embeddings", "activation", "norm_type", "traits", "primary_parent", "is_terminal", "is_root", "root_reason",
        "lane_root", "config_source", "provenance", "introduces"]
ALWAYS = ["attention_class", "swa", "is_moe", "mtp", "qk_norm", "gated_attention", "is_terminal", "is_root", "generation"]
nodes = []
for m in g["nodes"]:
    n = {k: m.get(k) for k in KEEP if m.get(k) not in (None, False, "", [])}
    for k in ALWAYS:
        n[k] = m[k]
    n["gallery"] = {k: m["gallery"].get(k) for k in ["card_url", "config_url", "report_url", "scale", "attention", "layer_mix"]}
    nodes.append(n)
edges = [{k: e[k] for k in ["source", "target", "type", "score", "jaccard", "shared", "traits", "why", "bonus"] if k in e} for e in g["edges"]]
out = {k: g[k] for k in ["generated", "source", "trait_labels", "trait_weights", "jaccard_min", "jaccard_min_same_org"]}
out["nodes"], out["edges"] = nodes, edges
js = "/* Generated by export_web.py — https://github.com/wenhaochai/llm-architecture-lineage */\nwindow.LLM_LINEAGE = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n"
targets = sys.argv[1:] or [f"{ROOT}/web/data.js"]
for t in targets:
    open(t, "w").write(js)
    print("wrote", t, len(js) // 1024, "KB,", len(nodes), "nodes,", len(edges), "edges")
