/* LLM architecture lineage — interactive DAG renderer.
   Data: window.LLM_LINEAGE (assets/data/llm-lineage.js), generated by
   https://github.com/wenhaochai/llm-architecture-lineage (extract.py + build_graph.py).
   No dependencies; SVG is drawn by hand. Bilingual labels resolve through t(en, zh). */
(function () {
  'use strict';
  var D = window.LLM_LINEAGE;
  if (!D) return;

  var nodes = D.nodes.slice().sort(function (a, b) { return a.date < b.date ? -1 : a.date > b.date ? 1 : a.key < b.key ? -1 : 1; });
  var byKey = {};
  nodes.forEach(function (n) { byKey[n.key] = n; });
  var edges = D.edges;
  var parentsOf = {}, childrenOf = {};
  nodes.forEach(function (n) { parentsOf[n.key] = []; childrenOf[n.key] = []; });
  edges.forEach(function (e) { parentsOf[e.target].push(e); childrenOf[e.source].push(e); });

  /* ---------- state ---------- */
  var state = { selected: 'kimi-k3', color: 'lineage', types: { variant: true, nearest: true, 'same-code': true, trait: true }, labels: false, hover: null };
  try { var q = /[?&]model=([a-z0-9-]+)/.exec(location.search); if (q && byKey[q[1]]) state.selected = q[1]; } catch (e) {}

  /* ---------- layout: generation columns, rows ordered by parent position ----------
     generation 0 = roots; every other node sits one column past its latest parent. */
  var gens = [];
  nodes.forEach(function (n) { if (gens.indexOf(n.generation) < 0) gens.push(n.generation); });
  gens.sort(function (a, b) { return a - b; });
  var W = 1120, ML = 30, MR = 30, MT = 34, MB = 18, ROW = 24;
  var maxCol = 0, colOf = {};
  gens.forEach(function (g) { colOf[g] = nodes.filter(function (n) { return n.generation === g; }); maxCol = Math.max(maxCol, colOf[g].length); });
  var H = MT + MB + Math.max(maxCol, 12) * ROW;
  var colX = {};
  gens.forEach(function (g, i) { colX[g] = ML + (W - ML - MR) * (gens.length === 1 ? 0.5 : i / (gens.length - 1)); });
  var pos = {};
  var laneOrder = {};
  nodes.forEach(function (n) { if (laneOrder[n.lane_root] === undefined) laneOrder[n.lane_root] = Object.keys(laneOrder).length; });
  gens.forEach(function (g) {
    var col = colOf[g];
    col.forEach(function (n) {
      var ps = parentsOf[n.key].filter(function (e) { return pos[e.source]; });
      if (ps.length) {
        var w = 0, s = 0;
        ps.forEach(function (e) { var wt = e.type === 'trait' ? 0.35 : 1; s += pos[e.source].y * wt; w += wt; });
        n._want = s / w;
      } else {
        n._want = H / 2 + (laneOrder[n.lane_root] - (Object.keys(laneOrder).length - 1) / 2) * ROW * 2;
      }
    });
    col.sort(function (a, b) { return a._want - b._want || (a.date < b.date ? -1 : a.date > b.date ? 1 : 0) || (a.key < b.key ? -1 : 1); });
    var span = (col.length - 1) * ROW;
    var mid = 0;
    col.forEach(function (n) { mid += n._want; });
    mid = col.length ? mid / col.length : H / 2;
    var y0 = Math.min(Math.max(mid - span / 2, MT), H - MB - span);
    col.forEach(function (n, i) { pos[n.key] = { x: colX[g], y: y0 + i * ROW }; });
  });
  (function stretch() {
    var lo = Infinity, hi = -Infinity;
    Object.keys(pos).forEach(function (k) { lo = Math.min(lo, pos[k].y); hi = Math.max(hi, pos[k].y); });
    if (hi - lo < ROW) return;
    var a = MT + 6, b = H - MB - 6;
    Object.keys(pos).forEach(function (k) { pos[k].y = a + (pos[k].y - lo) / (hi - lo) * (b - a); });
  })();

  /* ---------- lineage (ancestors + descendants of the selection) ---------- */
  function closure(key, dir) {
    var seen = {}, stack = [key], out = {};
    while (stack.length) {
      var k = stack.pop();
      if (seen[k]) continue;
      seen[k] = true;
      (dir === 'up' ? parentsOf[k] : childrenOf[k]).forEach(function (e) {
        if (!state.types[e.type]) return;
        out[e.source + '>' + e.target] = true;
        stack.push(dir === 'up' ? e.source : e.target);
      });
    }
    return { nodes: seen, edges: out };
  }

  /* ---------- palettes ---------- */
  var PAL = {
    attention: { GQA: '#4285F4', MLA: '#EA4335', MHA: '#F29900', MQA: '#188038', 'CSA/HCA': '#A142F4', CSA2: '#A142F4', CCA: '#00897B', 'none (mLSTM)': '#8A8791' },
    mixer: { 'attention-only': '#B9B4A6', gated_deltanet: '#4285F4', kda: '#EA4335', mamba2: '#188038', lightning: '#F29900', liv_conv: '#A142F4', mlstm: '#00897B' },
    ffn: { dense: '#B9B4A6', 'MoE': '#4285F4', 'MoE + shared expert': '#EA4335' }
  };
  var MIXER_LABEL = { 'attention-only': ['attention only', '纯注意力'], gated_deltanet: ['Gated DeltaNet', 'Gated DeltaNet'], kda: ['Kimi Delta Attention', 'Kimi Delta Attention'], mamba2: ['Mamba-2', 'Mamba-2'], lightning: ['Lightning Attention', 'Lightning Attention'], liv_conv: ['LIV convolution', 'LIV 卷积'], mlstm: ['mLSTM', 'mLSTM'] };
  function ffnClass(n) { return !n.is_moe ? 'dense' : (n.shared_experts ? 'MoE + shared expert' : 'MoE'); }
  function catOf(n) {
    if (state.color === 'attention') return n.attention_class;
    if (state.color === 'mixer') return n.hybrid_mixer || 'attention-only';
    if (state.color === 'ffn') return ffnClass(n);
    return null;
  }
  var BLUE = '#4285F4', DARK = '#1B4FB4', GREY = 'var(--lin-node, #C9C4B8)', GREY_EDGE = 'var(--lin-edge, rgba(120, 115, 105, 0.24))';

  /* ---------- helpers ---------- */
  var T = function (en, zh) { return (window.ArticleCharts && window.ArticleCharts.t) ? window.ArticleCharts.t(en, zh) : en; };
  function el(tag, attrs, children) {
    var e = tag === 'svg' || tag === 'g' || tag === 'path' || tag === 'circle' || tag === 'rect' || tag === 'text' || tag === 'line' || tag === 'title'
      ? document.createElementNS('http://www.w3.org/2000/svg', tag) : document.createElement(tag);
    if (attrs) Object.keys(attrs).forEach(function (k) { if (k === 'text') e.textContent = attrs[k]; else if (k === 'html') e.innerHTML = attrs[k]; else e.setAttribute(k, attrs[k]); });
    (children || []).forEach(function (c) { if (c) e.appendChild(c); });
    return e;
  }
  function esc(s) { return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]; }); }
  function shortName(n) { return n.title.replace(/\s*\([^)]*\)\s*$/, ''); }
  function attnLabel(n) {
    var a = n.attention_class;
    if (n.swa && n.swa_ratio) a += ' · ' + T('local:global ' + n.swa_local_layers + ':' + n.swa_global_layers, '局部:全局 ' + n.swa_local_layers + ':' + n.swa_global_layers);
    if (n.sparse_attention) a += ' · ' + n.sparse_attention;
    if (n.gated_attention) a += ' · ' + T('gated', '门控');
    return a;
  }
  function ffnLabel(n) {
    if (!n.is_moe) return T('dense', '稠密');
    var s = n.num_experts + ' ' + T('experts', '专家') + ', top-' + n.experts_per_tok;
    if (n.shared_experts) s += ' + ' + n.shared_experts + ' ' + T('shared', '共享');
    if (n.dense_prefix_layers) s += ', ' + n.dense_prefix_layers + ' ' + T('dense prefix', '稠密前缀层');
    return s;
  }
  function mixerLabel(n) {
    var m = n.hybrid_mixer;
    if (!m) return T('attention only', '纯注意力');
    var s = MIXER_LABEL[m] ? T(MIXER_LABEL[m][0], MIXER_LABEL[m][1]) : m;
    if (n.linear_layers && n.full_attention_layers_in_hybrid) s += ' ' + n.linear_layers + ' : ' + n.full_attention_layers_in_hybrid + ' ' + T('attention', '注意力');
    return s;
  }
  var EDGE_LABEL = {
    variant: ['same-day variant', '同日变体'], nearest: ['nearest config', '最近 config'], 'same-code': ['same modeling class', '同一建模类'], trait: ['trait origin', '特征来源']
  };

  /* ---------- render ---------- */
  var root, svgHost, panel, tip;
  function build(container) {
    root = container;
    root.innerHTML = '';
    root.className = 'lin';

    var bar = el('div', { 'class': 'lin-bar' });
    // search
    var search = el('input', { 'class': 'lin-search', id: 'lin-search', type: 'search', list: 'lin-models', placeholder: T('Find a model…', '搜索模型…'), 'aria-label': T('Find a model', '搜索模型') });
    var dl = el('datalist', { id: 'lin-models' });
    nodes.forEach(function (n) { dl.appendChild(el('option', { value: n.title })); });
    search.addEventListener('change', function () {
      var v = search.value.trim().toLowerCase();
      var hit = nodes.filter(function (n) { return n.title.toLowerCase() === v; })[0] || nodes.filter(function (n) { return n.title.toLowerCase().indexOf(v) >= 0; })[0];
      if (hit) { state.selected = hit.key; draw(); }
    });
    bar.appendChild(el('div', { 'class': 'lin-ctl' }, [search, dl]));
    // color mode
    var sel = el('select', { 'class': 'lin-select', id: 'lin-color', 'aria-label': T('Color by', '着色') });
    [['lineage', T('Color: lineage', '着色：谱系')], ['attention', T('Color: attention', '着色：注意力')], ['mixer', T('Color: sequence mixer', '着色：序列混合器')], ['ffn', T('Color: FFN', '着色：FFN')]].forEach(function (o) {
      var op = el('option', { value: o[0], text: o[1] }); if (o[0] === state.color) op.selected = true; sel.appendChild(op);
    });
    sel.addEventListener('change', function () { state.color = sel.value; draw(); });
    bar.appendChild(el('div', { 'class': 'lin-ctl' }, [sel]));
    // edge types
    var types = el('div', { 'class': 'lin-ctl lin-types' });
    ['same-code', 'nearest', 'variant', 'trait'].forEach(function (t) {
      var id = 'lin-t-' + t;
      var cb = el('input', { type: 'checkbox', id: id }); cb.checked = state.types[t];
      cb.addEventListener('change', function () { state.types[t] = cb.checked; draw(); });
      types.appendChild(el('label', { 'for': id, 'class': 'lin-type lin-type-' + t }, [cb, el('i'), el('span', { text: T(EDGE_LABEL[t][0], EDGE_LABEL[t][1]) })]));
    });
    bar.appendChild(types);
    // labels toggle
    var lb = el('input', { type: 'checkbox', id: 'lin-labels' }); lb.checked = state.labels;
    lb.addEventListener('change', function () { state.labels = lb.checked; draw(); });
    bar.appendChild(el('div', { 'class': 'lin-ctl' }, [el('label', { 'for': 'lin-labels', 'class': 'lin-type' }, [lb, el('span', { text: T('All names', '显示全部名称') })])]));
    root.appendChild(bar);

    var legend = el('div', { 'class': 'lin-legend', id: 'lin-legend' });
    root.appendChild(legend);

    svgHost = el('div', { 'class': 'lin-svg' });
    root.appendChild(svgHost);
    tip = el('div', { 'class': 'lin-tip', hidden: '' });
    svgHost.appendChild(tip);
    panel = el('div', { 'class': 'lin-panel' });
    root.appendChild(panel);
    draw();
  }

  function legendHTML() {
    var h = '';
    if (state.color === 'lineage') {
      h += item(DARK, 'sq', T('selected model', '选中模型')) + item(BLUE, 'c', T('its lineage: ancestors and descendants', '其谱系：祖先与后代')) + item(GREY, 'c', T('other models', '其他模型')) + item(GREY, 'sq', T('terminal node: no descendant in the gallery yet', '终端节点：图库中尚无后代'));
    } else {
      var pal = PAL[state.color];
      var used = {};
      nodes.forEach(function (n) { used[catOf(n)] = true; });
      Object.keys(pal).forEach(function (k) {
        if (!used[k]) return;
        var lab = state.color === 'mixer' && MIXER_LABEL[k] ? T(MIXER_LABEL[k][0], MIXER_LABEL[k][1]) : (state.color === 'ffn' ? T(k, { dense: '稠密', MoE: 'MoE', 'MoE + shared expert': 'MoE + 共享专家' }[k]) : k);
        h += item(pal[k], 'c', lab);
      });
      h += item(GREY, 'sq', T('square: terminal node', '方块：终端节点'));
    }
    return h;
    function item(color, shape, label) { return '<span class="li"><i class="' + shape + '" style="background:' + color + '"></i>' + esc(label) + '</span>'; }
  }

  function draw() {
    var lin = { nodes: {}, edges: {} };
    if (state.selected && byKey[state.selected]) {
      var up = closure(state.selected, 'up'), down = closure(state.selected, 'down');
      Object.keys(up.nodes).forEach(function (k) { lin.nodes[k] = true; }); Object.keys(down.nodes).forEach(function (k) { lin.nodes[k] = true; });
      Object.keys(up.edges).forEach(function (k) { lin.edges[k] = true; }); Object.keys(down.edges).forEach(function (k) { lin.edges[k] = true; });
    }
    document.getElementById('lin-legend').innerHTML = legendHTML();

    var svg = el('svg', { viewBox: '0 0 ' + W + ' ' + H, role: 'img', 'aria-label': T('Lineage graph of 103 open-weight LLM architectures', '103 个开源 LLM 架构的谱系图') });
    // generation axis
    gens.forEach(function (g) {
      var x = colX[g];
      svg.appendChild(el('line', { x1: x, y1: MT - 14, x2: x, y2: H - MB + 4, stroke: 'var(--rule-2)', 'stroke-width': 1 }));
      svg.appendChild(el('text', { x: x, y: 14, 'text-anchor': 'middle', 'font-size': 10, 'font-family': 'var(--font-mono)', fill: 'var(--ink-4)', text: g === 0 ? T('gen 0 · roots', '第 0 代 · 根') : T('gen ' + g, '第 ' + g + ' 代') }));
    });
    // edges: grey first, lineage on top
    var gEdges = el('g'), gEdgesHi = el('g');
    edges.forEach(function (e) {
      if (!state.types[e.type]) return;
      var a = pos[e.source], b = pos[e.target];
      if (!a || !b) return;
      var hi = lin.edges[e.source + '>' + e.target];
      var dx = Math.max(24, (b.x - a.x) * 0.5);
      var d = 'M' + a.x + ',' + a.y + ' C' + (a.x + dx) + ',' + a.y + ' ' + (b.x - dx) + ',' + b.y + ' ' + b.x + ',' + b.y;
      var p = el('path', { d: d, fill: 'none', 'class': 'lin-e lin-e-' + e.type + (hi ? ' hi' : ''),
        stroke: hi ? BLUE : GREY_EDGE, 'stroke-width': hi ? (e.type === 'trait' ? 1.4 : 1.8) : (e.type === 'same-code' ? 1.2 : 0.9),
        'stroke-dasharray': e.type === 'trait' ? '3 3' : (e.type === 'variant' ? '1.5 2.5' : 'none') });
      (hi ? gEdgesHi : gEdges).appendChild(p);
    });
    svg.appendChild(gEdges); svg.appendChild(gEdgesHi);
    // nodes
    var gN = el('g');
    nodes.forEach(function (n) {
      var p = pos[n.key];
      var isSel = n.key === state.selected, inLin = !!lin.nodes[n.key];
      var fill, stroke;
      if (state.color === 'lineage') { fill = isSel ? DARK : inLin ? BLUE : GREY; stroke = isSel ? DARK : inLin ? '#fff' : 'var(--paper)'; }
      else { fill = PAL[state.color][catOf(n)] || GREY; stroke = isSel ? DARK : inLin ? BLUE : 'var(--paper)'; }
      var r = isSel ? 7 : inLin ? 5.5 : 4.5;
      var g = el('g', { 'class': 'lin-n' + (isSel ? ' sel' : '') + (inLin ? ' lin' : ''), 'data-key': n.key, tabindex: 0, role: 'button', 'aria-label': n.title });
      var shape = n.is_terminal
        ? el('rect', { x: p.x - r, y: p.y - r, width: 2 * r, height: 2 * r, fill: fill, stroke: stroke, 'stroke-width': isSel ? 2 : inLin ? 1.5 : 1 })
        : el('circle', { cx: p.x, cy: p.y, r: r, fill: fill, stroke: stroke, 'stroke-width': isSel ? 2 : inLin ? 1.5 : 1 });
      g.appendChild(el('circle', { cx: p.x, cy: p.y, r: 11, fill: 'transparent' })); // hit target
      g.appendChild(shape);
      if (state.labels || isSel || (inLin && state.color === 'lineage')) {
        var right = p.x < W * 0.86;
        g.appendChild(el('text', { x: p.x + (right ? 9 : -9), y: p.y + 3.5, 'text-anchor': right ? 'start' : 'end', 'font-size': isSel ? 11 : 9.5, 'font-weight': isSel ? 600 : 400,
          fill: isSel ? 'var(--ink)' : inLin ? 'var(--ink-2)' : 'var(--ink-4)', 'paint-order': 'stroke', stroke: 'var(--paper)', 'stroke-width': 3, 'stroke-linejoin': 'round', text: shortName(n) }));
      }
      g.addEventListener('mouseenter', function (ev) { showTip(n, ev); });
      g.addEventListener('mousemove', function (ev) { moveTip(ev); });
      g.addEventListener('mouseleave', hideTip);
      g.addEventListener('click', function () { state.selected = n.key; draw(); });
      g.addEventListener('keydown', function (ev) { if (ev.key === 'Enter' || ev.key === ' ') { ev.preventDefault(); state.selected = n.key; draw(); } });
      gN.appendChild(g);
    });
    svg.appendChild(gN);
    var old = svgHost.querySelector('svg');
    if (old) svgHost.replaceChild(svg, old); else svgHost.insertBefore(svg, tip);
    renderPanel(lin);
  }

  /* ---------- tooltip ---------- */
  function showTip(n, ev) {
    tip.innerHTML = '<div class="th">' + esc(n.title) + '</div>' +
      '<div class="tr">' + esc(n.org) + ' · ' + esc(n.date) + ' · ' + T('generation ', '第 ') + n.generation + T('', ' 代') + '</div>' +
      '<div class="tr">' + esc(attnLabel(n)) + '</div>' +
      '<div class="tr">' + esc(mixerLabel(n)) + ' · ' + esc(ffnLabel(n)) + '</div>' +
      '<div class="tr">' + n.num_layers + ' ' + T('layers', '层') + ' · d=' + n.hidden_size + (n.num_heads ? ' · ' + n.num_heads + (n.num_kv_heads && n.attention_class !== 'MLA' ? '/' + n.num_kv_heads : '') + ' ' + T('heads', '头') : '') + '</div>' +
      '<div class="tr tr-hint">' + T('click to trace its lineage', '点击查看谱系') + '</div>';
    tip.hidden = false;
    moveTip(ev);
  }
  function moveTip(ev) {
    var r = svgHost.getBoundingClientRect();
    var x = ev.clientX - r.left, y = ev.clientY - r.top;
    var right = x < r.width * 0.6;
    tip.style.left = right ? (x + 14) + 'px' : 'auto';
    tip.style.right = right ? 'auto' : (r.width - x + 14) + 'px';
    tip.style.top = Math.max(0, y - 12) + 'px';
  }
  function hideTip() { tip.hidden = true; }

  /* ---------- detail panel ---------- */
  function renderPanel(lin) {
    var n = byKey[state.selected];
    if (!n) { panel.innerHTML = ''; return; }
    var kv = [
      [T('Organisation', '机构'), n.org], [T('Release', '发布'), n.date], [T('Generation', '代数'), n.generation + (n.is_root ? T(' (root)', '（根）') : '')],
      [T('Attention', '注意力'), attnLabel(n)], [T('Sequence mixer', '序列混合器'), mixerLabel(n)], [T('FFN', 'FFN'), ffnLabel(n)],
      [T('Depth / width', '深度 / 宽度'), n.num_layers + ' ' + T('layers', '层') + ', d = ' + n.hidden_size + (n.intermediate_size ? ', FFN ' + n.intermediate_size : '')],
      [T('Heads', '注意力头'), n.num_heads ? (n.num_heads + (n.num_kv_heads && n.attention_class !== 'MLA' ? ' query / ' + n.num_kv_heads + ' KV' : '') + (n.head_dim ? ', head_dim ' + n.head_dim : '')) : '–'],
      [T('Extras', '其他'), extras(n)],
      [T('Vocab / context', '词表 / 上下文'), (n.vocab_size ? n.vocab_size.toLocaleString() : '–') + ' / ' + (n.max_position_embeddings ? n.max_position_embeddings.toLocaleString() : '–')],
      [T('Modeling class', '建模类'), (n.architecture_class || '–') + (n.model_type ? ' · ' + n.model_type : '')]
    ];
    var h = '<div class="lin-ph"><h3>' + esc(n.title) + '</h3><div class="lin-links">' +
      (n.gallery.config_url ? '<a href="' + esc(n.gallery.config_url) + '" target="_blank" rel="noopener">config.json</a>' : '') +
      (n.gallery.report_url ? '<a href="' + esc(n.gallery.report_url) + '" target="_blank" rel="noopener">' + T('tech report', '技术报告') + '</a>' : '') +
      '<a href="' + esc(n.gallery.card_url) + '" target="_blank" rel="noopener">' + T('gallery card', '图库卡片') + '</a></div></div>';
    h += '<div class="lin-cols"><dl class="lin-kv">' + kv.map(function (p) { return '<div><dt>' + esc(p[0]) + '</dt><dd>' + esc(p[1]) + '</dd></div>'; }).join('') + '</dl>';
    h += '<div class="lin-rel">';
    h += '<h4>' + T('Parents', '父节点') + ' <span>' + parentsOf[n.key].filter(function (e) { return state.types[e.type]; }).length + '</span></h4>';
    var ps = parentsOf[n.key].filter(function (e) { return state.types[e.type]; }).sort(function (a, b) { return b.score - a.score; });
    if (!ps.length) h += '<p class="lin-note">' + esc(n.is_root ? T('Root node: ', '根节点：') + (n.root_reason || '') : T('No parent edge of the selected types.', '所选边类型下没有父节点。')) + '</p>';
    ps.forEach(function (e) { h += edgeRow(e, byKey[e.source], 'from'); });
    var cs = childrenOf[n.key].filter(function (e) { return state.types[e.type]; }).sort(function (a, b) { return byKey[a.target].date < byKey[b.target].date ? -1 : 1; });
    h += '<h4>' + T('Children', '子节点') + ' <span>' + cs.length + '</span></h4>';
    if (!cs.length) h += '<p class="lin-note">' + T('Terminal node: nothing later in the gallery descends from it.', '终端节点：图库中尚无更晚的模型继承它。') + '</p>';
    cs.forEach(function (e) { h += edgeRow(e, byKey[e.target], 'to'); });
    if (n.introduces && n.introduces.length) h += '<h4>' + T('First in the gallery', '图库首见') + '</h4><p class="lin-note">' + esc(n.introduces.join('; ')) + '</p>';
    h += '</div></div>';
    if (n.provenance) h += '<p class="lin-prov">' + T('Config provenance: ', '配置来源：') + esc(n.provenance) + '</p>';
    var nl = Object.keys(lin.nodes).length;
    h += '<p class="lin-prov">' + T('Lineage shown: ' + nl + ' models, ' + Object.keys(lin.edges).length + ' edges.', '当前谱系：' + nl + ' 个模型，' + Object.keys(lin.edges).length + ' 条边。') + '</p>';
    panel.innerHTML = h;
    panel.querySelectorAll('[data-go]').forEach(function (b) { b.addEventListener('click', function () { state.selected = b.getAttribute('data-go'); draw(); panel.scrollIntoView({ block: 'nearest' }); }); });
  }
  function extras(n) {
    var x = [];
    if (n.mtp) x.push('MTP' + (n.mtp_layers > 1 ? ' ×' + n.mtp_layers : ''));
    if (n.qk_norm) x.push('QK-Norm');
    if (n.nope && n.nope !== 'none') x.push('NoPE (' + n.nope + ')');
    if (n.mhc) x.push('mHC');
    if (n.kv_sharing) x.push(T('cross-layer KV sharing', '跨层 KV 共享'));
    if (n.per_layer_embeddings) x.push(T('per-layer embeddings', '逐层嵌入'));
    if (n.looped) x.push(T('looped depth', '循环深度'));
    if (n.shortconv) x.push('ShortConv');
    if (n.attention_sinks) x.push(T('attention sinks', '注意力汇'));
    if (n.chunked_attention) x.push(T('chunked attention', '分块注意力'));
    if (n.latent_moe) x.push('latent MoE');
    if (n.encoder_decoder) x.push(T('encoder-decoder', '编码器-解码器'));
    if (n.activation && n.activation !== 'silu') x.push(n.activation);
    if (n.norm_type === 'layernorm') x.push('LayerNorm');
    return x.length ? x.join(', ') : '–';
  }
  function edgeRow(e, other, dir) {
    var why;
    if (e.type === 'trait') why = T('earliest model with ', '最早具备 ') + (e.traits || []).join('; ');
    else if (e.type === 'variant') why = T('same-day release, same modeling class', '同日发布，同一建模类');
    else why = T('shares ', '共享 ') + (e.shared || []).length + ' / ' + Object.keys(other.traits).length + T(' traits', ' 个特征') + (e.bonus && Object.keys(e.bonus).length ? '; ' + Object.keys(e.bonus).join(', ') : '');
    return '<div class="lin-edge lin-edge-' + e.type + '"><button type="button" data-go="' + esc(other.key) + '">' + esc(other.title) + '</button>' +
      '<span class="lin-et">' + esc(T(EDGE_LABEL[e.type][0], EDGE_LABEL[e.type][1])) + ' · ' + e.score.toFixed(1) + '</span>' +
      '<span class="lin-why">' + esc(why) + '</span></div>';
  }

  /* ---------- metadata table ---------- */
  function buildTable(container) {
    var cols = [
      [T('Model', '模型'), function (n) { return n.title; }], [T('Org', '机构'), function (n) { return n.org; }], [T('Date', '日期'), function (n) { return n.date; }], [T('Gen', '代'), function (n) { return n.generation; }],
      [T('Attention', '注意力'), function (n) { return n.attention_class; }], [T('Local:global', '局部:全局'), function (n) { return n.swa && n.swa_local_layers ? n.swa_local_layers + ':' + n.swa_global_layers : (n.swa ? 'yes' : '–'); }],
      [T('Mixer', '混合器'), function (n) { return n.hybrid_mixer ? n.hybrid_mixer + (n.hybrid_ratio ? ' ' + n.linear_layers + ':' + n.full_attention_layers_in_hybrid : '') : '–'; }],
      [T('Sparse', '稀疏'), function (n) { return n.sparse_attention || '–'; }],
      [T('Experts', '专家'), function (n) { return n.is_moe ? n.num_experts + '/' + n.experts_per_tok + (n.shared_experts ? '+' + n.shared_experts : '') : '–'; }],
      ['MTP', function (n) { return n.mtp ? '✓' : '–'; }], ['QK-Norm', function (n) { return n.qk_norm ? '✓' : '–'; }], [T('Gated', '门控'), function (n) { return n.gated_attention ? '✓' : '–'; }],
      ['NoPE', function (n) { return n.nope && n.nope !== 'none' ? n.nope : '–'; }],
      ['L', function (n) { return n.num_layers; }], ['d', function (n) { return n.hidden_size; }], ['H/KV', function (n) { return n.num_heads ? n.num_heads + (n.num_kv_heads && n.attention_class !== 'MLA' ? '/' + n.num_kv_heads : '') : '–'; }],
      [T('Vocab', '词表'), function (n) { return n.vocab_size || '–'; }], [T('Class', '建模类'), function (n) { return n.architecture_class || '–'; }]
    ];
    var h = '<table><thead><tr>' + cols.map(function (c) { return '<th>' + esc(c[0]) + '</th>'; }).join('') + '</tr></thead><tbody>';
    nodes.forEach(function (n) { h += '<tr>' + cols.map(function (c, i) { return '<td' + (i === 0 ? ' class="m"' : '') + '>' + esc(c[1](n)) + '</td>'; }).join('') + '</tr>'; });
    container.innerHTML = h + '</tbody></table>';
  }

  window.Lineage = { build: build, table: buildTable, state: state, nodes: nodes, edges: edges };
})();
