/* LLM architecture lineage — interactive DAG renderer.
   Data: window.LLM_LINEAGE (assets/data/llm-lineage.js), generated by
   https://github.com/wenhaochai/llm-architecture-lineage (extract.py + build_graph.py).
   No dependencies; SVG is drawn by hand. Bilingual labels resolve through t(en, zh). */
(function () {
  'use strict';
  var D = window.LLM_LINEAGE;
  if (!D) return;

  var nodes = D.nodes.slice().sort(function (a, b) { return a.date < b.date ? -1 : a.date > b.date ? 1 : a.key < b.key ? -1 : 1; });
  var byKey = {};
  nodes.forEach(function (n) { byKey[n.key] = n; });
  var edges = D.edges;
  var parentsOf = {}, childrenOf = {};
  nodes.forEach(function (n) { parentsOf[n.key] = []; childrenOf[n.key] = []; });
  edges.forEach(function (e) { parentsOf[e.target].push(e); childrenOf[e.source].push(e); });

  /* ---------- state ---------- */
  var state = { selected: 'kimi-k3', hover: null };
  try { var q = /[?&]model=([a-z0-9-]+)/.exec(location.search); if (q && byKey[q[1]]) state.selected = q[1]; } catch (e) {}

  /* ---------- layout: generation columns, rows ordered by parent position ----------
     generation 0 = roots; every other node sits one column past its latest parent. */
  var gens = [];
  nodes.forEach(function (n) { if (gens.indexOf(n.generation) < 0) gens.push(n.generation); });
  gens.sort(function (a, b) { return a - b; });
  var W = 1120, ML = 30, MR = 30, MT = 34, MB = 18, ROW = 24;
  var maxCol = 0, colOf = {};
  gens.forEach(function (g) { colOf[g] = nodes.filter(function (n) { return n.generation === g; }); maxCol = Math.max(maxCol, colOf[g].length); });
  var H = MT + MB + Math.max(maxCol, 12) * ROW;
  var colX = {};
  gens.forEach(function (g, i) { colX[g] = ML + (W - ML - MR) * (gens.length === 1 ? 0.5 : i / (gens.length - 1)); });
  var pos = {};
  var laneOrder = {};
  nodes.forEach(function (n) { if (laneOrder[n.lane_root] === undefined) laneOrder[n.lane_root] = Object.keys(laneOrder).length; });
  gens.forEach(function (g) {
    var col = colOf[g];
    col.forEach(function (n) {
      var ps = parentsOf[n.key].filter(function (e) { return pos[e.source]; });
      if (ps.length) {
        var w = 0, s = 0;
        ps.forEach(function (e) { var wt = e.type === 'trait' ? 0.35 : 1; s += pos[e.source].y * wt; w += wt; }); // primary parents pull harder than trait origins
        n._want = s / w;
      } else {
        n._want = H / 2 + (laneOrder[n.lane_root] - (Object.keys(laneOrder).length - 1) / 2) * ROW * 2;
      }
    });
    col.sort(function (a, b) { return a._want - b._want || (a.date < b.date ? -1 : a.date > b.date ? 1 : 0) || (a.key < b.key ? -1 : 1); });
    var span = (col.length - 1) * ROW;
    var mid = 0;
    col.forEach(function (n) { mid += n._want; });
    mid = col.length ? mid / col.length : H / 2;
    var y0 = Math.min(Math.max(mid - span / 2, MT), H - MB - span);
    col.forEach(function (n, i) { pos[n.key] = { x: colX[g], y: y0 + i * ROW }; });
  });
  (function stretch() {
    var lo = Infinity, hi = -Infinity;
    Object.keys(pos).forEach(function (k) { lo = Math.min(lo, pos[k].y); hi = Math.max(hi, pos[k].y); });
    if (hi - lo < ROW) return;
    var a = MT + 6, b = H - MB - 6;
    Object.keys(pos).forEach(function (k) { pos[k].y = a + (pos[k].y - lo) / (hi - lo) * (b - a); });
  })();

  /* ---------- lineage (ancestors + descendants of the selection) ---------- */
  function closure(key, dir) {
    var seen = {}, stack = [key], out = {};
    while (stack.length) {
      var k = stack.pop();
      if (seen[k]) continue;
      seen[k] = true;
      (dir === 'up' ? parentsOf[k] : childrenOf[k]).forEach(function (e) {
        out[e.source + '>' + e.target] = true;
        stack.push(dir === 'up' ? e.source : e.target);
      });
    }
    return { nodes: seen, edges: out };
  }

  var MIXER_LABEL = { 'attention-only': ['attention only', '纯注意力'], gated_deltanet: ['Gated DeltaNet', 'Gated DeltaNet'], kda: ['Kimi Delta Attention', 'Kimi Delta Attention'], mamba2: ['Mamba-2', 'Mamba-2'], lightning: ['Lightning Attention', 'Lightning Attention'], liv_conv: ['LIV convolution', 'LIV 卷积'], mlstm: ['mLSTM', 'mLSTM'] };
  var ACCENT = 'var(--accent, #7A1A1A)', ACCENT_DEEP = 'var(--accent-hover, #5C1212)', GREY = 'var(--lin-node, #C9C4B8)', GREY_EDGE = 'var(--lin-edge, rgba(120, 115, 105, 0.24))';

  /* ---------- helpers ---------- */
  var T = function (en, zh) { return (window.ArticleCharts && window.ArticleCharts.t) ? window.ArticleCharts.t(en, zh) : en; };
  function el(tag, attrs, children) {
    var e = tag === 'svg' || tag === 'g' || tag === 'path' || tag === 'circle' || tag === 'rect' || tag === 'text' || tag === 'line' || tag === 'title'
      ? document.createElementNS('http://www.w3.org/2000/svg', tag) : document.createElement(tag);
    if (attrs) Object.keys(attrs).forEach(function (k) { if (k === 'text') e.textContent = attrs[k]; else if (k === 'html') e.innerHTML = attrs[k]; else e.setAttribute(k, attrs[k]); });
    (children || []).forEach(function (c) { if (c) e.appendChild(c); });
    return e;
  }
  function esc(s) { return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]; }); }
  function shortName(n) { return n.title.replace(/\s*\([^)]*\)\s*$/, ''); }
  function attnLabel(n) {
    var a = n.attention_class;
    if (n.swa && n.swa_ratio) a += ' · ' + T('local:global ' + n.swa_local_layers + ':' + n.swa_global_layers, '局部:全局 ' + n.swa_local_layers + ':' + n.swa_global_layers);
    if (n.sparse_attention) a += ' · ' + n.sparse_attention;
    if (n.gated_attention) a += ' · ' + T('gated', '门控');
    return a;
  }
  function ffnLabel(n) {
    if (!n.is_moe) return T('dense', '稠密');
    var s = n.num_experts + ' ' + T('experts', '专家') + ', top-' + n.experts_per_tok;
    if (n.shared_experts) s += ' + ' + n.shared_experts + ' ' + T('shared', '共享');
    if (n.dense_prefix_layers) s += ', ' + n.dense_prefix_layers + ' ' + T('dense prefix', '稠密前缀层');
    return s;
  }
  function mixerLabel(n) {
    var m = n.hybrid_mixer;
    if (!m) return T('attention only', '纯注意力');
    var s = MIXER_LABEL[m] ? T(MIXER_LABEL[m][0], MIXER_LABEL[m][1]) : m;
    if (n.linear_layers && n.full_attention_layers_in_hybrid) s += ' ' + n.linear_layers + ' : ' + n.full_attention_layers_in_hybrid + ' ' + T('attention', '注意力');
    return s;
  }

  /* ---------- render ---------- */
  var root, svgHost, panel, tip;
  function build(container) {
    root = container;
    root.innerHTML = '';
    root.className = 'lin';

    var bar = el('div', { 'class': 'lin-bar' });
    // search
    var search = el('input', { 'class': 'lin-search', id: 'lin-search', type: 'search', list: 'lin-models', placeholder: T('Find a model…', '搜索模型…'), 'aria-label': T('Find a model', '搜索模型') });
    var dl = el('datalist', { id: 'lin-models' });
    nodes.forEach(function (n) { dl.appendChild(el('option', { value: n.title })); });
    search.addEventListener('change', function () {
      var v = search.value.trim().toLowerCase();
      var hit = nodes.filter(function (n) { return n.title.toLowerCase() === v; })[0] || nodes.filter(function (n) { return n.title.toLowerCase().indexOf(v) >= 0; })[0];
      if (hit) { state.selected = hit.key; draw(); }
    });
    bar.appendChild(el('div', { 'class': 'lin-ctl' }, [search, dl]));
    root.appendChild(bar);

    svgHost = el('div', { 'class': 'lin-svg' });
    root.appendChild(svgHost);
    tip = el('div', { 'class': 'lin-tip', hidden: '' });
    svgHost.appendChild(tip);
    panel = el('div', { 'class': 'lin-panel' });
    root.appendChild(panel);
    draw();
  }

  function draw() {
    var lin = { nodes: {}, edges: {} };
    if (state.selected && byKey[state.selected]) {
      var up = closure(state.selected, 'up'), down = closure(state.selected, 'down');
      Object.keys(up.nodes).forEach(function (k) { lin.nodes[k] = true; }); Object.keys(down.nodes).forEach(function (k) { lin.nodes[k] = true; });
      Object.keys(up.edges).forEach(function (k) { lin.edges[k] = true; }); Object.keys(down.edges).forEach(function (k) { lin.edges[k] = true; });
    }

    var svg = el('svg', { viewBox: '0 0 ' + W + ' ' + H, role: 'img', 'aria-label': T('Lineage graph of 103 open-weight LLM architectures', '103 个开源 LLM 架构的谱系图') });
    // edges: grey first, lineage on top
    var gEdges = el('g'), gEdgesHi = el('g');
    edges.forEach(function (e) {
      var a = pos[e.source], b = pos[e.target];
      if (!a || !b) return;
      var hi = lin.edges[e.source + '>' + e.target];
      var dx = Math.max(24, (b.x - a.x) * 0.5);
      var d = 'M' + a.x + ',' + a.y + ' C' + (a.x + dx) + ',' + a.y + ' ' + (b.x - dx) + ',' + b.y + ' ' + b.x + ',' + b.y;
      var p = el('path', { d: d, fill: 'none', 'class': 'lin-e' + (hi ? ' hi' : ''), stroke: hi ? ACCENT : GREY_EDGE, 'stroke-width': hi ? 1.6 : 1, 'stroke-opacity': hi ? 0.85 : 1 });
      (hi ? gEdgesHi : gEdges).appendChild(p);
    });
    svg.appendChild(gEdges); svg.appendChild(gEdgesHi);
    // nodes
    var gN = el('g');
    nodes.forEach(function (n) {
      var p = pos[n.key];
      var isSel = n.key === state.selected, inLin = !!lin.nodes[n.key];
      var fill = isSel ? ACCENT_DEEP : inLin ? ACCENT : GREY, stroke = isSel ? ACCENT_DEEP : 'var(--paper)';
      var r = isSel ? 7 : inLin ? 5.5 : 4.5;
      var g = el('g', { 'class': 'lin-n' + (isSel ? ' sel' : '') + (inLin ? ' lin' : ''), 'data-key': n.key, tabindex: 0, role: 'button', 'aria-label': n.title });
      var shape = n.is_terminal
        ? el('rect', { x: p.x - r, y: p.y - r, width: 2 * r, height: 2 * r, fill: fill, stroke: stroke, 'stroke-width': isSel ? 2 : inLin ? 1.5 : 1 })
        : el('circle', { cx: p.x, cy: p.y, r: r, fill: fill, stroke: stroke, 'stroke-width': isSel ? 2 : inLin ? 1.5 : 1 });
      g.appendChild(el('circle', { cx: p.x, cy: p.y, r: 11, fill: 'transparent' })); // hit target
      g.appendChild(shape);
      if (isSel || inLin) {
        var right = p.x < W * 0.86;
        g.appendChild(el('text', { x: p.x + (right ? 9 : -9), y: p.y + 3.5, 'text-anchor': right ? 'start' : 'end', 'font-size': isSel ? 11 : 9.5, 'font-weight': isSel ? 600 : 400,
          fill: isSel ? 'var(--ink)' : inLin ? 'var(--ink-2)' : 'var(--ink-4)', 'paint-order': 'stroke', stroke: 'var(--paper)', 'stroke-width': 3, 'stroke-linejoin': 'round', text: shortName(n) }));
      }
      g.addEventListener('mouseenter', function (ev) { showTip(n, ev); });
      g.addEventListener('mousemove', function (ev) { moveTip(ev); });
      g.addEventListener('mouseleave', hideTip);
      g.addEventListener('click', function () { state.selected = n.key; draw(); });
      g.addEventListener('keydown', function (ev) { if (ev.key === 'Enter' || ev.key === ' ') { ev.preventDefault(); state.selected = n.key; draw(); } });
      gN.appendChild(g);
    });
    svg.appendChild(gN);
    var old = svgHost.querySelector('svg');
    if (old) svgHost.replaceChild(svg, old); else svgHost.insertBefore(svg, tip);
    renderPanel(lin);
  }

  /* ---------- tooltip ---------- */
  function signature(n) {
    var parts = [n.attention_class === 'none (mLSTM)' ? 'mLSTM' : n.attention_class];
    if (n.swa && n.swa_local_layers) parts.push(T('local/global ', '局部/全局 ') + n.swa_local_layers + ':' + n.swa_global_layers);
    if (n.sparse_attention) parts.push(n.sparse_attention);
    if (n.hybrid_mixer && n.hybrid_mixer !== 'mlstm') parts.push((MIXER_LABEL[n.hybrid_mixer] ? T(MIXER_LABEL[n.hybrid_mixer][0], MIXER_LABEL[n.hybrid_mixer][1]) : n.hybrid_mixer) + (n.linear_layers && n.full_attention_layers_in_hybrid ? ' ' + n.linear_layers + ':' + n.full_attention_layers_in_hybrid : ''));
    parts.push(n.is_moe ? 'MoE ' + n.num_experts + '/' + n.experts_per_tok + (n.shared_experts ? '+' + n.shared_experts : '') : T('dense', '稠密'));
    return parts.join('  ·  ');
  }
  function showTip(n, ev) {
    tip.innerHTML = '<div class="tp-eyebrow">' + esc(n.org) + '<span>' + esc(n.date) + '</span></div>' +
      '<div class="tp-title">' + esc(n.title) + '</div>' +
      '<div class="tp-sig">' + esc(signature(n)) + '</div>' +
      '<div class="tp-foot"><span>' + n.num_layers + ' ' + T('layers', '层') + ' · d ' + n.hidden_size + '</span><span>' + T('generation ', '第 ') + n.generation + T('', ' 代') + '</span></div>';
    tip.hidden = false;
    moveTip(ev);
  }
  function moveTip(ev) {
    var r = svgHost.getBoundingClientRect();
    var x = ev.clientX - r.left, y = ev.clientY - r.top;
    var right = x < r.width * 0.6;
    tip.style.left = right ? (x + 14) + 'px' : 'auto';
    tip.style.right = right ? 'auto' : (r.width - x + 14) + 'px';
    tip.style.top = Math.max(0, y - 12) + 'px';
  }
  function hideTip() { tip.hidden = true; }

  /* ---------- detail panel ---------- */
  function renderPanel(lin) {
    var n = byKey[state.selected];
    if (!n) { panel.innerHTML = ''; return; }
    var kv = [
      [T('Attention', '注意力'), attnLabel(n)], [T('Sequence mixer', '序列混合器'), mixerLabel(n)], [T('FFN', 'FFN'), ffnLabel(n)],
      [T('Depth / width', '深度 / 宽度'), n.num_layers + ' ' + T('layers', '层') + ', d = ' + n.hidden_size + (n.intermediate_size ? ', FFN ' + n.intermediate_size : '') + (n.moe_intermediate_size ? ', ' + T('expert', '专家') + ' ' + n.moe_intermediate_size : '')],
      [T('Heads', '注意力头'), n.num_heads ? (n.num_heads + (n.num_kv_heads && n.attention_class !== 'MLA' ? ' query / ' + n.num_kv_heads + ' KV' : '') + (n.head_dim ? ', head_dim ' + n.head_dim : '')) : '–'],
      n.kv_lora_rank ? [T('Latent ranks', '潜在秩'), 'kv ' + n.kv_lora_rank + (n.q_lora_rank ? ', q ' + n.q_lora_rank : '') + (n.qk_rope_head_dim != null ? ', rope ' + n.qk_rope_head_dim + ' / nope ' + n.qk_nope_head_dim : '') + (n.v_head_dim ? ', v ' + n.v_head_dim : '')] : null,
      [T('Positions', '位置编码'), (n.position_encoding === 'rope' ? 'RoPE' + (n.rope_theta ? ' θ = ' + Number(n.rope_theta).toLocaleString() : '') + (n.rope_scaling_type ? ', ' + n.rope_scaling_type + (n.rope_scaling_factor ? ' ×' + n.rope_scaling_factor : '') : '') + (n.partial_rotary ? T(', partial', '，部分维度') : '') : n.position_encoding) + (n.nope && n.nope !== 'none' ? ' · NoPE ' + n.nope : '')],
      [T('Extras', '其他'), extras(n)],
      [T('Vocab / context', '词表 / 上下文'), (n.vocab_size ? n.vocab_size.toLocaleString() : '–') + ' / ' + (n.max_position_embeddings ? n.max_position_embeddings.toLocaleString() : '–') + (n.tie_embeddings ? T(', tied embeddings', '，共享嵌入') : '')],
      [T('Modeling class', '建模类'), (n.architecture_class || '–') + (n.model_type ? ' · ' + n.model_type : '')]
    ].filter(Boolean);
    var h = '<div class="lin-ph"><div class="tp-eyebrow">' + esc(n.org) + '<span>' + esc(n.date) + '</span><span>' + T('generation ', '第 ') + n.generation + T('', ' 代') + (n.is_root ? T(' · root', ' · 根') : '') + '</span></div>' +
      '<h3>' + esc(n.title) + '</h3><p class="lin-sig">' + esc(signature(n)) + '</p><div class="lin-links">' +
      (n.gallery.config_url ? '<a href="' + esc(n.gallery.config_url) + '" target="_blank" rel="noopener">config.json</a>' : '') +
      (n.gallery.report_url ? '<a href="' + esc(n.gallery.report_url) + '" target="_blank" rel="noopener">' + T('tech report', '技术报告') + '</a>' : '') +
      '<a href="' + esc(n.gallery.card_url) + '" target="_blank" rel="noopener">' + T('gallery card', '图库卡片') + '</a></div></div>';
    h += '<div class="lin-cols"><dl class="lin-kv">' + kv.map(function (p) { return '<div><dt>' + esc(p[0]) + '</dt><dd>' + esc(p[1]) + '</dd></div>'; }).join('') + '</dl>';
    h += '<div class="lin-rel">';
    var ps = parentsOf[n.key].slice().sort(function (a, b) { return b.score - a.score; });
    h += '<h4>' + T('Parents', '父节点') + ' <span>' + ps.length + '</span></h4>';
    if (!ps.length) h += '<p class="lin-note">' + esc(T('Root: ', '根节点：') + (n.root_reason || '')) + '</p>';
    ps.forEach(function (e) { h += edgeRow(e, byKey[e.source]); });
    var cs = childrenOf[n.key].slice().sort(function (a, b) { return byKey[a.target].date < byKey[b.target].date ? -1 : 1; });
    h += '<h4>' + T('Children', '子节点') + ' <span>' + cs.length + '</span></h4>';
    if (!cs.length) h += '<p class="lin-note">' + T('Terminal node: nothing in the gallery descends from it yet.', '终端节点：图库中尚无模型继承它。') + '</p>';
    cs.forEach(function (e) { h += edgeRow(e, byKey[e.target]); });
    if (n.introduces && n.introduces.length) h += '<h4>' + T('First in the gallery', '图库首见') + '</h4><p class="lin-note">' + esc(n.introduces.join('; ')) + '</p>';
    h += '</div></div>';
    if (n.provenance) h += '<p class="lin-prov">' + T('Config provenance: ', '配置来源：') + esc(n.provenance) + '</p>';
    // the complete config, every key
    var keys = Object.keys(n.config_full || {}).sort();
    h += '<details class="lin-full"><summary>' + T('Full config', '完整 config') + ' <span>' + keys.length + ' ' + T('keys', '个字段') + '</span></summary><dl class="lin-raw">';
    keys.forEach(function (k) { h += '<div><dt>' + esc(k) + '</dt><dd>' + esc(fmtVal(n.config_full[k])) + '</dd></div>'; });
    h += '</dl></details>';
    var nl = Object.keys(lin.nodes).length;
    h += '<p class="lin-prov">' + T('Lineage shown: ' + nl + ' models, ' + Object.keys(lin.edges).length + ' edges.', '当前谱系：' + nl + ' 个模型，' + Object.keys(lin.edges).length + ' 条边。') + '</p>';
    panel.innerHTML = h;
    panel.querySelectorAll('[data-go]').forEach(function (b) { b.addEventListener('click', function () { state.selected = b.getAttribute('data-go'); draw(); panel.scrollIntoView({ block: 'nearest' }); }); });
  }
  function fmtVal(v) {
    if (v === null || v === undefined) return 'null';
    if (typeof v === 'object' && v._list_len) return T('list of ' + v._list_len + ': ', '共 ' + v._list_len + ' 项：') + Object.keys(v._counts).map(function (k) { return k + ' ×' + v._counts[k]; }).join(', ');
    if (typeof v === 'object') return JSON.stringify(v);
    return String(v);
  }
  function extras(n) {
    var x = [];
    if (n.mtp) x.push('MTP' + (n.mtp_layers > 1 ? ' ×' + n.mtp_layers : ''));
    if (n.qk_norm) x.push('QK-Norm');
    if (n.nope && n.nope !== 'none') x.push('NoPE (' + n.nope + ')');
    if (n.mhc) x.push('mHC');
    if (n.kv_sharing) x.push(T('cross-layer KV sharing', '跨层 KV 共享'));
    if (n.per_layer_embeddings) x.push(T('per-layer embeddings', '逐层嵌入'));
    if (n.looped) x.push(T('looped depth', '循环深度'));
    if (n.shortconv) x.push('ShortConv');
    if (n.attention_sinks) x.push(T('attention sinks', '注意力汇'));
    if (n.chunked_attention) x.push(T('chunked attention', '分块注意力'));
    if (n.latent_moe) x.push('latent MoE');
    if (n.encoder_decoder) x.push(T('encoder-decoder', '编码器-解码器'));
    if (n.activation && n.activation !== 'silu') x.push(n.activation);
    if (n.norm_type === 'layernorm') x.push('LayerNorm');
    return x.length ? x.join(', ') : '–';
  }
  function edgeRow(e, other) {
    var why;
    if (e.type === 'trait') why = T('earliest gallery model with ', '图库中最早具备 ') + (e.traits || []).join('; ');
    else if (e.type === 'variant') why = T('same-day release, same modeling class', '同日发布，同一建模类');
    else if (e.type === 'same-code') why = T('closest config, same modeling class; shares ', '最近 config，同一建模类；共享 ') + (e.shared || []).length + ' / ' + Object.keys(other.traits).length + T(' traits', ' 个特征');
    else why = T('closest config; shares ', '最近 config；共享 ') + (e.shared || []).length + ' / ' + Object.keys(other.traits).length + T(' traits', ' 个特征');
    return '<div class="lin-edge"><button type="button" data-go="' + esc(other.key) + '">' + esc(other.title) + '</button><span class="lin-why">' + esc(why) + '</span></div>';
  }

  /* ---------- metadata table ---------- */
  function buildTable(container) {
    function v(x) { return x === null || x === undefined || x === false ? '–' : (x === true ? '✓' : x); }
    var cols = [
      [T('Model', '模型'), function (n) { return n.title; }], [T('Org', '机构'), function (n) { return n.org; }], [T('Date', '日期'), function (n) { return n.date; }], [T('Gen', '代'), function (n) { return n.generation; }],
      [T('Class', '建模类'), function (n) { return v(n.architecture_class); }], ['model_type', function (n) { return v(n.model_type); }],
      [T('Attention', '注意力'), function (n) { return n.attention_class; }], ['L', function (n) { return v(n.num_layers); }], ['d', function (n) { return v(n.hidden_size); }], ['FFN', function (n) { return v(n.intermediate_size); }],
      ['H', function (n) { return v(n.num_heads); }], ['KV', function (n) { return n.attention_class === 'MLA' ? 'latent' : v(n.num_kv_heads); }], ['head_dim', function (n) { return v(n.head_dim); }],
      ['q_lora', function (n) { return v(n.q_lora_rank); }], ['kv_lora', function (n) { return v(n.kv_lora_rank); }], ['rope/nope dim', function (n) { return n.qk_rope_head_dim != null ? n.qk_rope_head_dim + '/' + v(n.qk_nope_head_dim) : '–'; }],
      [T('Local:global', '局部:全局'), function (n) { return n.swa && n.swa_local_layers ? n.swa_local_layers + ':' + n.swa_global_layers : (n.swa ? '✓' : '–'); }], [T('Window', '窗口'), function (n) { return v(n.sliding_window); }],
      [T('Mixer', '混合器'), function (n) { return n.hybrid_mixer ? n.hybrid_mixer + (n.linear_layers && n.full_attention_layers_in_hybrid ? ' ' + n.linear_layers + ':' + n.full_attention_layers_in_hybrid : '') : '–'; }],
      [T('Sparse', '稀疏'), function (n) { return v(n.sparse_attention) + (n.index_topk ? ' top-' + n.index_topk : ''); }],
      [T('Experts', '专家'), function (n) { return n.is_moe ? n.num_experts + '/' + n.experts_per_tok + (n.shared_experts ? '+' + n.shared_experts : '') : '–'; }],
      [T('Expert FFN', '专家 FFN'), function (n) { return v(n.moe_intermediate_size); }], [T('Dense prefix', '稠密前缀'), function (n) { return v(n.dense_prefix_layers); }],
      [T('Router', '路由'), function (n) { return n.is_moe ? [n.router_scoring, n.topk_method, n.expert_groups && n.expert_groups > 1 ? n.expert_groups + 'g/' + v(n.topk_group) : null, n.routed_scaling_factor != null ? '×' + n.routed_scaling_factor : null].filter(Boolean).join(' ') || '–' : '–'; }],
      ['MTP', function (n) { return n.mtp ? (n.mtp_layers || 1) : '–'; }], ['QK-Norm', function (n) { return v(n.qk_norm); }], [T('Gated', '门控'), function (n) { return v(n.gated_attention); }],
      ['NoPE', function (n) { return n.nope && n.nope !== 'none' ? n.nope : '–'; }], ['rope_theta', function (n) { return v(n.rope_theta); }], [T('RoPE scaling', 'RoPE 缩放'), function (n) { return n.rope_scaling_type ? n.rope_scaling_type + (n.rope_scaling_factor ? ' ×' + n.rope_scaling_factor : '') : '–'; }],
      [T('Partial RoPE', '部分 RoPE'), function (n) { return n.partial_rotary_factor != null && n.partial_rotary_factor !== 1 ? n.partial_rotary_factor : (n.rotary_dim ? n.rotary_dim + 'd' : '–'); }],
      [T('Activation', '激活'), function (n) { return v(n.activation); }], [T('Norm', '归一化'), function (n) { return v(n.norm_type) + (n.norm_eps ? ' ' + n.norm_eps : ''); }],
      [T('Attn bias', '注意力偏置'), function (n) { return v(n.attention_bias); }], [T('Tied emb.', '共享嵌入'), function (n) { return v(n.tie_embeddings); }],
      [T('Vocab', '词表'), function (n) { return v(n.vocab_size); }], [T('Context', '上下文'), function (n) { return v(n.max_position_embeddings); }],
      ['mHC', function (n) { return n.mhc ? (n.hc_streams || '✓') : '–'; }], [T('KV share', 'KV 共享'), function (n) { return v(n.kv_shared_layers); }], ['PLE', function (n) { return v(n.hidden_size_per_layer_input); }],
      [T('Loops', '循环'), function (n) { return v(n.loop_passes); }], [T('Sinks', '注意力汇'), function (n) { return v(n.attention_sinks); }], [T('Softcap', '软上限'), function (n) { return v(n.final_logit_softcapping); }],
      ['Mamba', function (n) { return n.mamba_num_heads ? n.mamba_num_heads + 'h×' + v(n.mamba_head_dim) + ' s' + v(n.ssm_state_size) : '–'; }],
      [T('Linear attn', '线性注意力'), function (n) { return n.linear_num_value_heads ? v(n.linear_num_key_heads) + '/' + n.linear_num_value_heads + 'h×' + v(n.linear_value_head_dim) : '–'; }],
      [T('Conv', '卷积'), function (n) { return v(n.conv_kernel); }], ['dtype', function (n) { return v(n.dtype); }], [T('Keys', '字段数'), function (n) { return v(n.num_config_keys); }]
    ];
    var h = '<table><thead><tr>' + cols.map(function (c) { return '<th>' + esc(c[0]) + '</th>'; }).join('') + '</tr></thead><tbody>';
    nodes.forEach(function (n) { h += '<tr>' + cols.map(function (c, i) { return '<td' + (i === 0 ? ' class="m"' : '') + '>' + esc(c[1](n)) + '</td>'; }).join('') + '</tr>'; });
    container.innerHTML = h + '</tbody></table>';
  }

  window.Lineage = { build: build, table: buildTable, state: state, nodes: nodes, edges: edges };
})();
