/* LLM architecture lineage — online DAG construction + renderer.
   Data: window.LLM_LINEAGE (assets/data/llm-lineage.js), generated by
   https://github.com/wenhaochai/llm-architecture-lineage (extract.py + export_web.py).

   The graph is built here, in release order: each model is compared with every model
   already placed (except scale copies), attaches under the one that needs the fewest
   design changes, gets one extra edge from the earliest model that already carried each
   mechanism it adds, and hangs off GPT-2 XL when even the closest design needs more
   changes than the threshold (32). build_graph.py mirrors this for the repository data. */
(function () {
  'use strict';
  var D = window.LLM_LINEAGE;
  if (!D) return;

  function paramsTotal(n) { var m = /^\s*([\d.]+)\s*([BMT])/.exec((n.gallery && n.gallery.scale) || ''); return m ? parseFloat(m[1]) * { M: 1e6, B: 1e9, T: 1e12 }[m[2]] : 0; }
  // release order; on one day the larger model comes first, so a smaller sibling becomes its scale copy
  var nodes = D.nodes.slice().sort(function (a, b) { return a.date < b.date ? -1 : a.date > b.date ? 1 : paramsTotal(b) - paramsTotal(a) || (a.key < b.key ? -1 : 1); });
  var byKey = {};
  nodes.forEach(function (n) { byKey[n.key] = n; });
  var T = function (en, zh) { return (window.ArticleCharts && window.ArticleCharts.t) ? window.ArticleCharts.t(en, zh) : en; };

  /* ---------- schema: which canonical fields count ---------- */
  var SCALE = {}, TUNING = {}, SKIP = {}, PRESENCE = {}, MECH = {}, RESTATED = {}, COND = D.schema_conditional || {}, ORDER = [];
  (D.schema_scale || []).forEach(function (f) { SCALE[f] = 1; });
  (D.schema_tuning || []).forEach(function (f) { TUNING[f] = 1; });
  (D.schema_not_a_change || []).forEach(function (f) { SKIP[f] = 1; });
  (D.schema_presence || []).forEach(function (f) { PRESENCE[f] = 1; });
  (D.schema_mechanism || []).forEach(function (f) { MECH[f] = 1; });
  (D.schema_restated || []).forEach(function (f) { RESTATED[f] = 1; });
  function mechCount(ch) { var m = 0; ch.forEach(function (c) { if (MECH[c.field]) m++; }); return m; }
  Object.keys(D.schema_groups || {}).forEach(function (g) { D.schema_groups[g].forEach(function (f) { ORDER.push(f); }); });

  function absent(v) {
    return v === undefined || v === null || v === false || v === 0 || v === '' || (Array.isArray(v) && !v.length) ||
      (typeof v === 'object' && !Array.isArray(v) && !v._list_len && !v._raw && !Object.keys(v).length);
  }
  function shape(v) {
    if (v && typeof v === 'object' && v._list_len) return Object.keys(v._counts).sort().concat([v._ratio]); // a longer copy of the same schedule is no change
    if (v && typeof v === 'object' && v._indices) return 'indices';
    if (Array.isArray(v)) return v.slice().sort();
    return v;
  }
  function stable(v) { // JSON with sorted keys, so key order in a config never counts as a change
    if (Array.isArray(v)) return '[' + v.map(stable).join(',') + ']';
    if (v && typeof v === 'object') return '{' + Object.keys(v).sort().map(function (k) { return JSON.stringify(k) + ':' + stable(v[k]); }).join(',') + '}';
    return JSON.stringify(v);
  }
  function same(a, b) { return stable(shape(a)) === stable(shape(b)); }
  var changeCache = {};
  function changes(x, p) {
    // design changes of x relative to p, in schema order: {field, kind: add | drop | change}
    var ck = x.key + '|' + p.key;
    if (changeCache[ck]) return changeCache[ck];
    var a = p.config_canonical || {}, b = x.config_canonical || {}, out = [];
    ORDER.forEach(function (k) {
      if (SKIP[k] || TUNING[k] || RESTATED[k] || (SCALE[k] && !PRESENCE[k])) return;
      if (COND[k] && !same(a[COND[k]], b[COND[k]])) return; // the mechanism itself already counted this
      var va = a[k], vb = b[k], hasA = !absent(va), hasB = !absent(vb);
      if (hasA && hasB) { if (!SCALE[k] && !same(va, vb)) out.push({ field: k, kind: 'change', from: va, to: vb }); }
      else if (hasB) out.push({ field: k, kind: 'add', to: vb });
      else if (hasA) out.push({ field: k, kind: 'drop', from: va });
    });
    changeCache[ck] = out;
    return out;
  }

  /* ---------- online construction ---------- */
  var state = { selected: 'deepseek-v4-1-flash', threshold: D.origin_threshold || 32 };
  try { var q = /[?&]model=([a-z0-9-]+)/.exec(location.search); if (q && byKey[q[1]]) state.selected = q[1]; } catch (e) {}
  var edges, parentsOf, childrenOf, visible = nodes;
  function computeGraph(thr) {
    edges = []; parentsOf = {}; childrenOf = {};
    nodes.forEach(function (n) { parentsOf[n.key] = []; childrenOf[n.key] = []; n.parent = null; n.parentVia = null; n.scale_copy = false; n.changes = []; n.generation = 0; n.is_root = false; });
    var placed = [], origin = nodes[0];
    origin.is_root = true;
    placed.push(origin);
    function addEdge(src, dst, type, fields, n) {
      var e = { source: src.key, target: dst.key, type: type, fields: fields || [], n: n, mech: type === 'trait' ? null : mechCount(dst.changes) };
      edges.push(e); parentsOf[dst.key].push(e); childrenOf[src.key].push(e);
    }
    nodes.slice(1).forEach(function (x) {
      var eligible = placed.filter(function (p) { return !p.scale_copy; });
      // rank: fewer mechanism-level changes, then fewer changes overall, then same modeling class, same organisation, earlier release
      var best = null, bestKey = null, bestN = Infinity;
      eligible.forEach(function (p) {
        var ch = changes(x, p);
        var key = [mechCount(ch), ch.length, -(p.architecture_class === x.architecture_class), -(p.org === x.org)];
        var better = !best;
        if (best) { for (var i = 0; i < key.length; i++) { if (key[i] !== bestKey[i]) { better = key[i] < bestKey[i]; break; } } if (!better && key.join() === bestKey.join() && (p.date < best.date || (p.date === best.date && p.key < best.key))) better = true; } // exact ties go to the earlier release
        if (better) { best = p; bestKey = key; bestN = ch.length; }
      });
      if (!best || bestN > thr) {
        x.parent = origin.key; x.changes = changes(x, origin);
        addEdge(origin, x, 'origin', [], x.changes.length);
      } else {
        x.parent = best.key; x.changes = changes(x, best);
        if (bestN === 0) x.scale_copy = true;
        addEdge(best, x, 'parent', [], bestN);
      }
      // second kind of edge: the earliest placed model that already carried what x adds or switches to
      var origins = {};
      x.changes.forEach(function (c) {
        if (c.kind === 'drop' || !MECH[c.field]) return; // only mechanisms get an origin edge
        var src = null;
        eligible.forEach(function (p) {
          if (p.key === x.parent) return;
          var v = (p.config_canonical || {})[c.field];
          if (absent(v)) return;
          if (!same(v, c.to)) return; // the origin must carry the same value, not just the field
          if (!src || p.date < src.date || (p.date === src.date && p.key < src.key)) src = p;
        });
        if (src) (origins[src.key] = origins[src.key] || []).push(c.field);
      });
      Object.keys(origins).forEach(function (k) { addEdge(byKey[k], x, 'trait', origins[k], origins[k].length); });
      x.generation = 1 + Math.max.apply(null, parentsOf[x.key].map(function (e) { return byKey[e.source].generation; }));
      placed.push(x);
    });
    // transitive reduction: an edge A -> C is dropped when A already reaches C through another parent of C
    var anc = {};
    nodes.forEach(function (n) {
      anc[n.key] = {};
      parentsOf[n.key].forEach(function (e) { anc[n.key][e.source] = 1; Object.keys(anc[e.source] || {}).forEach(function (k) { anc[n.key][k] = 1; }); });
    });
    edges = edges.filter(function (e) {
      var redundant = parentsOf[e.target].some(function (o) { return o !== e && anc[o.source] && anc[o.source][e.source]; });
      if (redundant) {
        childrenOf[e.source] = childrenOf[e.source].filter(function (c) { return c !== e; });
        parentsOf[e.target] = parentsOf[e.target].filter(function (p) { return p !== e; });
        if (e.type !== 'trait') { // the closest design is still reached, through another parent
          var via = parentsOf[e.target].filter(function (o) { return anc[o.source] && anc[o.source][e.source]; })[0];
          byKey[e.target].parentVia = via ? via.source : null;
        }
      }
      return !redundant;
    });
    // a scale copy is the same design: fold it into the model it copies; that node keeps the earliest name
    nodes.forEach(function (n) { n.aliases = []; n.hidden = false; });
    nodes.forEach(function (n) {
      if (!n.scale_copy) return;
      var p = byKey[n.parent];
      p.aliases.push(n); n.hidden = true;
      edges = edges.filter(function (e) { return e.target !== n.key; });
      parentsOf[n.key] = [];
      childrenOf[p.key] = childrenOf[p.key].filter(function (e) { return e.target !== n.key; });
    });
    visible = nodes.filter(function (n) { return !n.hidden; });
    if (byKey[state.selected] && byKey[state.selected].hidden) state.selected = byKey[state.selected].parent;
    nodes.forEach(function (n) { n.is_terminal = childrenOf[n.key].length === 0; });
  }

  /* ---------- layout: generation columns, each centred on the middle axis ---------- */
  var W = 1120, ML = 30, MR = 30, MT = 24, MB = 18, ROW = 24, H, pos, gens;
  function layout() {
    gens = [];
    visible.forEach(function (n) { if (gens.indexOf(n.generation) < 0) gens.push(n.generation); });
    gens.sort(function (a, b) { return a - b; });
    var colOf = {}, maxCol = 0;
    gens.forEach(function (g) { colOf[g] = visible.filter(function (n) { return n.generation === g; }); maxCol = Math.max(maxCol, colOf[g].length); });
    H = MT + MB + Math.max(maxCol, 12) * ROW;
    var colX = {}, mid = H / 2;
    gens.forEach(function (g, i) { colX[g] = ML + (W - ML - MR) * (gens.length === 1 ? 0.5 : i / (gens.length - 1)); });
    pos = {};
    gens.forEach(function (g) {
      var col = colOf[g];
      col.forEach(function (n) {
        var ps = parentsOf[n.key].filter(function (e) { return pos[e.source]; });
        if (ps.length) { var w = 0, s = 0; ps.forEach(function (e) { var wt = e.type === 'trait' ? 0.35 : 1; s += pos[e.source].y * wt; w += wt; }); n._want = s / w; }
        else n._want = mid;
      });
      // order by where the parents sit, then centre the whole column on the axis so the figure is symmetric
      col.sort(function (a, b) { return a._want - b._want || (a.date < b.date ? -1 : a.date > b.date ? 1 : 0) || (a.key < b.key ? -1 : 1); });
      var y0 = mid - (col.length - 1) * ROW / 2;
      col.forEach(function (n, i) { pos[n.key] = { x: colX[g], y: y0 + i * ROW }; });
    });
  }

  function closure(key, dir) {
    var seen = {}, stack = [key], out = {};
    while (stack.length) {
      var k = stack.pop();
      if (seen[k]) continue;
      seen[k] = true;
      (dir === 'up' ? parentsOf[k] : childrenOf[k]).forEach(function (e) { out[e.source + '>' + e.target] = true; stack.push(dir === 'up' ? e.source : e.target); });
    }
    return { nodes: seen, edges: out };
  }

  /* ---------- helpers ---------- */
  var MIXER_LABEL = { gated_deltanet: ['Gated DeltaNet', 'Gated DeltaNet'], kda: ['Kimi Delta Attention', 'Kimi Delta Attention'], mamba2: ['Mamba-2', 'Mamba-2'], lightning: ['Lightning Attention', 'Lightning Attention'], liv_conv: ['LIV convolution', 'LIV 卷积'], mlstm: ['mLSTM', 'mLSTM'] };
  var ACCENT = 'var(--accent, #7A1A1A)', ACCENT_DEEP = 'var(--accent-hover, #5C1212)', GREY = 'var(--lin-node, #C9C4B8)', GREY_EDGE = 'var(--lin-edge, rgba(120, 115, 105, 0.24))';
  function el(tag, attrs, children) {
    var svgTags = { svg: 1, g: 1, path: 1, circle: 1, rect: 1, text: 1, line: 1 };
    var e = svgTags[tag] ? document.createElementNS('http://www.w3.org/2000/svg', tag) : document.createElement(tag);
    if (attrs) Object.keys(attrs).forEach(function (k) { if (k === 'text') e.textContent = attrs[k]; else if (k === 'html') e.innerHTML = attrs[k]; else e.setAttribute(k, attrs[k]); });
    (children || []).forEach(function (c) { if (c) e.appendChild(c); });
    return e;
  }
  function esc(s) { return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]; }); }
  function shortName(n) {
    // parameter counts stay out of names; they come back only when two drawn nodes would otherwise read the same
    var nm = n.name || n.title;
    var clash = visible.some(function (x) { return x !== n && !x.hidden && (x.name || x.title) === nm; });
    return clash ? n.title : nm;
  }
  function fmtVal(v) {
    if (v === null || v === undefined) return 'null';
    if (Array.isArray(v)) return v.map(fmtVal).join(', ');
    if (typeof v === 'object' && v._raw) return Object.keys(v._raw).map(function (k) { return k + ' = ' + fmtVal(v._raw[k]); }).join(' · ');
    if (typeof v === 'object' && v._list_len) return Object.keys(v._counts).map(function (k) { return v._counts[k] + ' × ' + k; }).join(' · ') + ' (' + v._list_len + T(' layers', ' 层') + (v._ratio ? ', ' + v._ratio : '') + ')';
    if (typeof v === 'object' && v._indices) return v._indices + T(' layers', ' 层') + (v._step ? T(', every ' + v._step, '，每 ' + v._step + ' 层一个') : '') + ' (' + v._min + '–' + v._max + ')';
    if (typeof v === 'object') return Object.keys(v).map(function (k) { return k + ' = ' + fmtVal(v[k]); }).join(' · ');
    return String(v);
  }
  function short(v) {
    if (v === true) return T('on', '开'); if (v === false) return T('off', '关'); if (v === null || v === undefined) return 'null';
    if (v && typeof v === 'object' && v._list_len) return Object.keys(v._counts).join('/') + (v._ratio ? ' ' + v._ratio : '');
    if (v && typeof v === 'object' && v._indices) return v._indices + T(' layers', ' 层');
    if (typeof v === 'object') return T('changed', '有变化');
    return String(v);
  }
  function signature(n) {
    var parts = [n.attention_class === 'none (mLSTM)' ? 'mLSTM' : n.attention_class];
    if (n.swa && n.swa_local_layers) parts.push(T('local/global ', '局部/全局 ') + n.swa_local_layers + ':' + n.swa_global_layers);
    if (n.sparse_attention) parts.push(n.sparse_attention);
    if (n.hybrid_mixer && n.hybrid_mixer !== 'mlstm') parts.push((MIXER_LABEL[n.hybrid_mixer] ? T(MIXER_LABEL[n.hybrid_mixer][0], MIXER_LABEL[n.hybrid_mixer][1]) : n.hybrid_mixer) + (n.linear_layers && n.full_attention_layers_in_hybrid ? ' ' + n.linear_layers + ':' + n.full_attention_layers_in_hybrid : ''));
    parts.push(n.is_moe ? 'MoE ' + n.num_experts + '/' + n.experts_per_tok + (n.shared_experts ? '+' + n.shared_experts : '') : T('dense', '稠密'));
    return parts.join('  ·  ');
  }
  function changeText(c) {
    if (c.kind === 'add') return '+ ' + c.field + (c.to === true || SCALE[c.field] || typeof c.to === 'object' ? '' : ' ' + short(c.to));
    if (c.kind === 'drop') return '− ' + c.field;
    var a = short(c.from), b = short(c.to);
    return a === b ? c.field + ' ' + b : c.field + ' ' + a + ' → ' + b;
  }
  function aliasHTML(n, cls) {
    if (!n.aliases || !n.aliases.length) return '';
    return '<p class="' + cls + '"><span class="sp-vs">' + T('same design', '同一设计') + '</span>' + n.aliases.map(function (a) { return esc(shortName(a)) + ' <i>' + esc(a.date) + '</i>'; }).join(' · ') + '</p>';
  }
  function noveltyHTML(n, cls, limit) {
    var items;
    if (n.is_root) items = [signature(n)];
    else if (!n.changes.length) items = [T('same design, different scale', '设计相同，只有规模不同')];
    else items = n.changes.slice().sort(function (a, b) { return (MECH[b.field] ? 1 : 0) - (MECH[a.field] ? 1 : 0); }).map(changeText);
    if (limit && items.length > limit) items = items.slice(0, limit).concat([T('+' + (n.changes.length - limit) + ' more', '还有 ' + (n.changes.length - limit) + ' 项')]);
    var head = n.is_root ? T('origin', '起点') : T('from ', '承自 ') + esc(shortName(byKey[n.parent]));
    return '<p class="' + cls + '"><span class="sp-vs">' + head + '</span>' + esc(items.join(' · ')) + '</p>';
  }

  /* ---------- render ---------- */
  var root, svgHost, panel, tip;
  function build(container) {
    root = container;
    root.innerHTML = '';
    root.className = 'lin';
    svgHost = el('div', { 'class': 'lin-svg' });
    root.appendChild(svgHost);
    tip = el('div', { 'class': 'lin-tip', hidden: '' });
    svgHost.appendChild(tip);
    panel = el('div', { 'class': 'lin-panel' });
    root.appendChild(panel);
    rebuild();
  }
  function rebuild() {
    computeGraph(state.threshold);
    layout();
    draw();
  }

  function draw() {
    var lin = { nodes: {}, edges: {} };
    if (state.selected && byKey[state.selected]) {
      var up = closure(state.selected, 'up'), down = closure(state.selected, 'down');
      Object.keys(up.nodes).forEach(function (k) { lin.nodes[k] = true; }); Object.keys(down.nodes).forEach(function (k) { lin.nodes[k] = true; });
      Object.keys(up.edges).forEach(function (k) { lin.edges[k] = true; }); Object.keys(down.edges).forEach(function (k) { lin.edges[k] = true; });
    }
    var svg = el('svg', { viewBox: '0 0 ' + W + ' ' + H, role: 'img', 'aria-label': T('Lineage graph of open-weight LLM architectures', '开源 LLM 架构谱系图') });
    var gEdges = el('g'), gEdgesHi = el('g');
    edges.forEach(function (e) {
      var a = pos[e.source], b = pos[e.target];
      if (!a || !b) return;
      var hi = lin.edges[e.source + '>' + e.target];
      var p = el('path', { d: 'M' + a.x + ',' + a.y + ' L' + b.x + ',' + b.y, fill: 'none', 'class': 'lin-e' + (hi ? ' hi' : ''), stroke: hi ? ACCENT : GREY_EDGE, 'stroke-width': hi ? 1.6 : 1, 'stroke-opacity': hi ? 0.85 : 1 });
      (hi ? gEdgesHi : gEdges).appendChild(p);
    });
    svg.appendChild(gEdges); svg.appendChild(gEdgesHi);
    var gN = el('g');
    visible.forEach(function (n) {
      var p = pos[n.key];
      var isSel = n.key === state.selected, inLin = !!lin.nodes[n.key];
      var fill = isSel ? ACCENT_DEEP : inLin ? ACCENT : GREY, stroke = isSel ? ACCENT_DEEP : 'var(--paper)';
      var r = isSel ? 7.5 : inLin ? 6 : 5;
      var g = el('g', { 'class': 'lin-n' + (isSel ? ' sel' : '') + (inLin ? ' lin' : ''), 'data-key': n.key, tabindex: 0, role: 'button', 'aria-label': shortName(n) });
      var sw = isSel ? 2 : inLin ? 1.5 : 1, shapeEl;
      if (n.is_terminal) shapeEl = el('rect', { x: p.x - r, y: p.y - r, width: 2 * r, height: 2 * r, fill: fill, stroke: stroke, 'stroke-width': sw });
      else shapeEl = el('circle', { cx: p.x, cy: p.y, r: r, fill: fill, stroke: stroke, 'stroke-width': sw });
      g.appendChild(el('circle', { cx: p.x, cy: p.y, r: 11, fill: 'transparent' }));
      g.appendChild(shapeEl);
      if (isSel || inLin) {
        var right = p.x < W * 0.86;
        g.appendChild(el('text', { x: p.x + (right ? 9 : -9), y: p.y + 3.5, 'text-anchor': right ? 'start' : 'end', 'font-size': isSel ? 13 : 11, 'font-weight': isSel ? 600 : 400,
          fill: isSel ? 'var(--ink)' : inLin ? 'var(--ink-2)' : 'var(--ink-4)', 'paint-order': 'stroke', stroke: 'var(--paper)', 'stroke-width': 3, 'stroke-linejoin': 'round', text: shortName(n) }));
      }
      g.addEventListener('mouseenter', function (ev) { showTip(n, ev); });
      g.addEventListener('mousemove', moveTip);
      g.addEventListener('mouseleave', hideTip);
      g.addEventListener('click', function () { state.selected = n.key; draw(); });
      g.addEventListener('keydown', function (ev) { if (ev.key === 'Enter' || ev.key === ' ') { ev.preventDefault(); state.selected = n.key; draw(); } });
      gN.appendChild(g);
    });
    svg.appendChild(gN);
    var old = svgHost.querySelector('svg');
    if (old) svgHost.replaceChild(svg, old); else svgHost.insertBefore(svg, tip);
    renderPanel();
  }

  /* ---------- tooltip ---------- */
  function showTip(n, ev) {
    tip.innerHTML = '<div class="tp-eyebrow">' + esc(n.org) + '<span>' + esc(n.date) + '</span></div>' +
      '<div class="tp-title">' + esc(shortName(n)) + '</div>' + aliasHTML(n, 'tp-alias') +
      '<div class="tp-foot"><span>' + esc((n.gallery.scale || '').replace(/ \(.*\)$/, '')) + '</span><span>' + n.num_layers + ' ' + T('layers', '层') + ' · d ' + n.hidden_size + '</span></div>';
    tip.hidden = false;
    moveTip(ev);
  }
  function moveTip(ev) {
    var r = svgHost.getBoundingClientRect();
    var x = ev.clientX - r.left, y = ev.clientY - r.top;
    var right = x < r.width * 0.6;
    tip.style.left = right ? (x + 14) + 'px' : 'auto';
    tip.style.right = right ? 'auto' : (r.width - x + 14) + 'px';
    tip.style.top = Math.max(0, y - 12) + 'px';
  }
  function hideTip() { tip.hidden = true; }

  /* ---------- model card ---------- */
  function renderPanel() {
    var n = byKey[state.selected];
    if (!n) { panel.innerHTML = ''; return; }
    var dash = '–';
    var cc = n.config_canonical || {}, rawOf = n.config_canonical_raw_key || {};
    var changed = {};
    n.changes.forEach(function (c) { changed[c.field] = c.kind; });
    function val(v) {
      if (v === true) return T('on', '开'); if (v === false) return T('off', '关');
      if (typeof v === 'number') return Number.isInteger(v) && Math.abs(v) >= 10000 ? v.toLocaleString() : String(v);
      return fmtVal(v);
    }
    function specRows(fields) {
      return fields.filter(function (f) { return f in cc; }).map(function (f) {
        var r = rawOf[f], mark = changed[f] ? '<em class="sp-chg">' + (changed[f] === 'add' ? '+' : '·') + '</em>' : '';
        var v = val(cc[f]);
        return '<div class="sp-row' + (changed[f] ? ' is-changed' : '') + (v.length > 28 ? ' is-long' : '') + '"><span>' + mark + esc(f) + (r && r !== f ? '<i>' + esc(r) + '</i>' : '') + '</span><b>' + esc(v) + '</b></div>';
      }).join('');
    }
    var sections = D.schema_sections || {}, groups = D.schema_groups || {};
    var body = '';
    Object.keys(sections).forEach(function (sec) {
      var subs = sections[sec].map(function (g) { return { name: g.indexOf(' › ') > 0 ? g.split(' › ')[1] : null, rows: specRows(groups[g]) }; }).filter(function (x) { return x.rows; });
      if (!subs.length) return;
      body += '<div class="sp-sec"><h4>' + esc(sec) + '</h4>' + subs.map(function (x) { return '<div class="sp-group">' + (x.name ? '<h5>' + esc(x.name) + '</h5>' : '') + x.rows + '</div>'; }).join('') + '</div>';
    });
    function sameName(o) { return nodes.some(function (x) { return x !== o && shortName(x) === shortName(o); }); }
    function why(e) {
      if (e.type === 'origin') return T('origin · ' + e.n + ' changes, over the threshold', '起点 · ' + e.n + ' 项改动，超过阈值');
      if (e.type === 'trait') return T('first with ', '首见 ') + e.fields.join(', ');
      if (e.n === 0) return T('same design', '设计相同');
      return T('closest design · ' + (e.mech ? e.mech + ' mechanism · ' : '') + e.n + (e.n === 1 ? ' change' : ' changes'), '最近设计 · ' + (e.mech ? e.mech + ' 项机制 · ' : '') + e.n + ' 项改动');
    }
    function rel(title, list, side) {
      var h = '<div class="sp-rel"><h4>' + esc(title) + '</h4>';
      if (!list.length && !(side === 'up' && n.parentVia)) h += '<p class="sp-none">' + esc(side === 'up' ? (n.is_root ? T('origin of the graph', '图的起点') : dash) : T('none yet', '暂无')) + '</p>';
      if (side === 'up' && n.parentVia) {
        var pp = byKey[n.parent];
        h += '<div class="sp-node"><button type="button" data-go="' + esc(pp.key) + '">' + esc(shortName(pp)) + '</button><span>' + esc(T('closest design · ' + n.changes.length + ' changes · reached through ' + shortName(byKey[n.parentVia]), '最近设计 · ' + n.changes.length + ' 项改动 · 经 ' + shortName(byKey[n.parentVia]) + ' 到达')) + '</span></div>';
      }
      list.forEach(function (e) {
        var o = byKey[side === 'up' ? e.source : e.target];
        h += '<div class="sp-node"><button type="button" data-go="' + esc(o.key) + '">' + esc(shortName(o)) + (o.gallery.scale && sameName(o) ? ' <i>' + esc(o.gallery.scale.split(',')[0]) + '</i>' : '') + '</button><span>' + esc(why(e)) + '</span></div>';
      });
      return h + '</div>';
    }
    var ps = parentsOf[n.key].slice().sort(function (a, b) { return (a.type === 'trait') - (b.type === 'trait'); });
    var cs = childrenOf[n.key].slice().sort(function (a, b) { return byKey[a.target].date < byKey[b.target].date ? -1 : 1; });
    var nCanon = Object.keys(cc).length;
    var h = '<div class="sp-head"><div><div class="tp-eyebrow">' + esc(n.org) + '<span>' + esc(n.date) + '</span>' + (n.gallery.scale ? '<span>' + esc(n.gallery.scale) + '</span>' : '') + '</div><h3>' + esc(shortName(n)) + '</h3>' + aliasHTML(n, 'sp-alias') + noveltyHTML(n, 'sp-sig') + '</div>' +
      '<div class="sp-links">' + (n.gallery.config_url ? '<a href="' + esc(n.gallery.config_url) + '" target="_blank" rel="noopener">config.json</a>' : '') +
      (n.gallery.report_url ? '<a href="' + esc(n.gallery.report_url) + '" target="_blank" rel="noopener">' + T('report', '技术报告') + '</a>' : '') +
      '<a href="' + esc(n.gallery.card_url) + '" target="_blank" rel="noopener">' + T('gallery', '图库') + '</a></div></div>';
    h += '<div class="sp-rels">' + rel(T('Parents', '父节点'), ps, 'up') + rel(T('Children', '子节点'), cs, 'down') + '</div>';
    h += '<div class="sp-config"><div class="tp-eyebrow">' + T('Config after key drop and renaming', '清理并统一命名后的 config') + '<span>' + nCanon + ' ' + T('fields', '个字段') + '</span><span>' + (n.num_architecture_keys || nCanon) + ' ' + T('architecture keys in the config', '个架构 key') + '</span>' + (n.provenance ? '<span>' + esc(T('provenance: ', '来源：') + n.provenance) + '</span>' : '') + '</div>' + body + '</div>';
    panel.innerHTML = h;
    panel.querySelectorAll('[data-go]').forEach(function (b) { b.addEventListener('click', function () { state.selected = b.getAttribute('data-go'); draw(); panel.scrollIntoView({ block: 'nearest' }); }); });
  }

  window.Lineage = { build: build, state: state, nodes: nodes, changes: changes, rebuild: rebuild, edges: function () { return edges; } };
})();
